name: geosiren
channels:
  - pytorch
  - conda-forge
dependencies:
  - python[version='>=3.11']
  - pytorch::pytorch[version='>=2.0.1']
  - pytorch::torchvision[version='>=0.15']
  - pytorch-cuda[version='>=11.8']
  # - comet_ml::comet_ml
  - colorcet
  - matplotlib
  - numpy
  - rasterio
  - tifffile
  - verde
  - black
  - flake8
  - ipykernel
  - tqdm
  - rope