name: geosiren
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python[version='>=3.11']
  - pytorch::pytorch[version='>=1.13']
  - pytorch::torchvision[version='>=0.14']
  - pytorch-cuda[version='>=11.7']
  - comet_ml::comet_ml
  - colorcet
  - matplotlib
  - numpy
  - rasterio
  - tifffile
  - verde
  - black
  - flake8
  - jupyter
  - ipykernel
  - nb_conda
  - tqdm
  - rope